# Example multistrap configuration file for the squeeze shortcut.

[General]
arch=amd64
directory=/tmp/system
# same as --tidy-up option if set to true
cleanup=true
# same as --no-auth option if set to true
# keyring packages listed in each bootstrap will
# still be installed.
noauth=true
# whether to add the /suite to be explicit about where apt
# needs to look for packages. Default is false.
explicitsuite=false
# extract all downloaded archives (default is true)
unpack=true
# the order of sections is not important.
# the bootstrap option determines which repository
# is used to calculate the list of Priority: required packages.
bootstrap=Debian
aptsources=Debian

[Debian]
packages=apt udev iproute2
source=http://localhost
#source=http://http.debian.net/debian
#keyring=debian-archive-keyring
suite=stretch
