#!/bin/sh

# Call this to load all modules 
# and bring up devices

load_modules()
{    
    modules="ahci sd_mod virtio_blk virtio_pci ext4 isofs squashfs"

    for mod in $modules; 
    do      
        echo "Loading $mod ..."
        modprobe $mod 
    done
}

#Disable kernel messages from popping onto the screen
echo 0 > /proc/sys/kernel/printk

PATH=/bin:/usr/bin:/sbin:/usr/sbin
export PATH

test  ! -d /dev && mkdir /dev && chmod 0755 /dev

mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
mount -t devtmpfs dev /dev -o mode=0755,nosuid

if [ ! -e /dev/sr0 ]; then
    mknod /dev/sr0 b 11 0
fi

mkdir cdrom
mount -t iso9660 /dev/sr0 cdrom

if [ ! e /dev/loop0 ]; then
    mknod /dev/loop0 b 7 0
fi

losetup /dev/loop0 /cdrom/rootfs.sq
mkdir install_root
mount -t squashfs /dev/loop0 install_root

exec /bin/sh
